jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: generate and commit diagrams
        uses: abekoh/commit-plantuml-action@1.0.1
        with:
          botEmail: ${{ secrets.BOT_EMAIL }}
          botGithubToken: ${{ secrets.GITHUB_TOKEN }}
          enableReviewComment: true
